codecrunchers/codecrunchers/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.conf.urls import include
from django.conf import settings
import www.views
from django.views.static import serve
from django.contrib.auth import views
from loginform import LoginForm

admin.site.site_header = settings.ADMIN_SITE_HEADER
admin.site.index_title = settings.ADMIN_INDEX_TITLE
admin.site.site_title = settings.ADMIN_SITE_TITLE
urlpatterns = [
    #url(r'^$', include('www.urls')),
    url(r'^$', www.views.index, name='sitehome'),
	url(r'^jet/', include('jet.urls', 'jet')),  # Django JET URLS
    url(r'^admin/', admin.site.urls),
    url(r'^console/', include('codeconsole.urls', 'cc')),
    url(r'^evaluate/', include('evaluation.urls', 'ev')),
	url(r'^static/(?P<path>.*)$', serve, {'document_root': settings.STATIC_ROOT}),
    # url(r'^login/$', views.login, {'template_name':'www/login.html', 'authentication_form':LoginForm}, name='login'),
    # url(r'^logout/$', views.logout, {'next_page':'/login'}),
    url(r'^accounts/', include('registration.backends.hmac.urls')),
    url(r'^profile/$', www.views.profile, name='profile'),
    # Social_Auth
    url(r'^oauth/', include('social_django.urls', namespace='social')),
    url(r'^settings/$', www.views.settings, name='settings'),
    url(r'^settings/password/$', www.views.password, name='password'),
    url(r'^media/(?P<path>.*)$', serve, {'document_root': settings.MEDIA_ROOT}),
    url(r'^leaderboard/$', www.views.leaderboard, name='leaderboard'),
    url(r'^dashboard/$', www.views.dashboard, name='dashboard'),
    url(r'^manageprofile/$', www.views.create_profile, name='create_profile'),
]

codecrunchers/www/urls.py
from django.conf.urls import url
from www import views

urlpatterns = [
    #    url(r'^$', views.index.as_view(), 'index'),
]

codecrunchers/www/models.py
from __future__ import unicode_literals

from django.db import models
from django.contrib.auth.models import AbstractUser
from django.contrib.auth.models import User

# Create your models here.
def get_user_avatar_name(instance, filename):
    print filename
    parts = filename.split('.')
    extension = parts[-1]
    print extension
    new_name = 'profileimages/' + str(instance.user) + '.' + extension
    return new_name
class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    Student = "S"
    Candidate = "C"
    Employer = "E"
    Faculty = "F"
    USER_TYPES = (
    (Student, "Student"),
    (Candidate, "Candidate"),
    (Employer, "Employer"),
    (Faculty, "Faculty"),
    )

    user_type = models.CharField(max_length=255, choices=USER_TYPES, default=Student)
    user_avatar = models.ImageField(upload_to = get_user_avatar_name, default='profileimages/anonymous.jpg')
    experience_points = models.IntegerField(default=0, verbose_name="Experience Points")
    def __unicode__(self):
        return self.user.username

    def get_usertype_verbose(self):
        return dict(self.USER_TYPES).get(self.user_type)

codecrunchers/www/forms.py
from django.forms import ModelForm
from www.models import Profile
from django import forms

class ProfileForm(ModelForm):
    
    class Meta:
        model = Profile
        fields = ['user_type','user_avatar']
        widgets = {
            #'user_type': TextInput(attrs={'class': 'form-control'}),
            #'user_avatar': FileField(attrs={'class': "form-control"}),
            }

codecrunchers/www/views.py
from calendar import calendar
from django.db.models.functions import TruncMonth, Extract
from django.shortcuts import HttpResponse, render, redirect, HttpResponseRedirect, reverse
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import AdminPasswordChangeForm, PasswordChangeForm
from django.contrib.auth import update_session_auth_hash
from django.contrib import messages
from graphos.renderers.base import BaseChart
from graphos.renderers.highcharts import BaseHighCharts
from social_django.models import UserSocialAuth
from .models import Profile
from evaluation.models import ContestParticipant
from django.contrib.auth.models import User
from evaluation.models import Submission, ConsoleLanguage, Problem
from graphos.sources.model import ModelDataSource, SimpleDataSource
from graphos.renderers import morris, highcharts
from django.db.models import Max, Aggregate, Sum, Count
from graphos.renderers.gchart import LineChart
from django.db.models.functions import ExtractYear, ExtractMonth, ExtractDay, ExtractWeekDay
from www.forms import ProfileForm
# Create your views here.
def index(request):
    # return  HttpResponse("<h1>YASH<h1>")
    return render(request, 'www/home.html', {})

# Social_Auth Login and Management
@login_required
def settings(request):
    user = request.user

    try:
        github_login = user.social_auth.get(provider='github')
    except UserSocialAuth.DoesNotExist:
        github_login = None
    
    try:
        facebook_login = user.social_auth.get(provider='facebook')
    except UserSocialAuth.DoesNotExist:
        facebook_login = None
    
    can_disconnect = (user.social_auth.count() > 1 or user.has_usable_password())
    
    return render(request, 'www/settings.html', {
        'github_login': github_login,
        'facebook_login': facebook_login,
        'can_disconnect': can_disconnect
    })

@login_required
def password(request):
    if request.user.has_usable_password():
        PasswordForm = PasswordChangeForm
    else:
        PasswordForm = AdminPasswordChangeForm
    
    if request.method == 'POST':
        form = PasswordForm(request.user, request.POST)
        if form.is_valid():
            form.save()
            update_session_auth_hash(request, form.user)
            messages.success(request, 'Your password was successfully updated!')
            return redirect('password')
        else:
            messages.error(request, 'Please Correct the Error Below.')
    else:
        form = PasswordForm(request.user)
    
    return render(request, 'www/password.html', {form:'form'})

@login_required
def profile(request):
    # Difficulty wise submissions pie chart
    query_set = Submission.objects.select_related().filter(sub_made_by = request.user).values('prob__difficulty').annotate(subcount = Count('prob__difficulty'))
    print query_set
    options = {
        'title':'Difficulty wise submissions',
        'subtitle': "Total submissions: " + str(Submission.objects.filter(sub_made_by = request.user).count()),
    }
    data = list()
    row = list()
    data.append(['Difficulty', 'submissions'])
    for query in query_set:
        row.append(get_difficulty_verbose(query['prob__difficulty']))
        row.append(query['subcount'])
        data.append(row)
        row = list()
    print data
    data_source = SimpleDataSource(data)
    chart = highcharts.ColumnChart(data_source, options=options)
    chart.html_id = "difficultychart"
    # Topic wise submissions pie chart
    query_set = Submission.objects.select_related().filter(sub_made_by = request.user).values('prob__topic__topic_name').annotate(count = Count('prob__topic__topic_name'))
    options = {
        'title':'Topic wise submissions',
        'subtitle': "Total submissions: " + str(Submission.objects.filter(sub_made_by = request.user).count()),
    }
    row = list()
    data = list()
    data.append(['Topic', 'Submissions'])
    for query in query_set:
        row.append(query['prob__topic__topic_name'])
        row.append(query['count'])
        data.append(row)
        row = list()
    data_source = SimpleDataSource(data)
    topic_chart = highcharts.PieChart(data_source, options=options)
    topic_chart.html_id = "otherchart"
    # Other chart
    query_set = Submission.objects.select_related().filter(sub_made_by = request.user).annotate(month = TruncMonth('attempted')).values('month').annotate(submissions = Count('id'))[:12]
    options = {
        'title':'Monthly  submissions',
        'subtitle': "Total submissions: " + str(Submission.objects.filter(sub_made_by = request.user).count()),
    }
    data = list()
    data.append(['Month', 'Submissions'])
    for query in  query_set:
        count  = query['submissions']
        month = str(query['month'].strftime('%B')) + ", " +  str(query['month'].strftime('%Y'))
        row.append(month)
        row.append(count)
        data.append(row)
        row = list()
    print data
    data_source = SimpleDataSource(data)
    monthly_chart = highcharts.LineChart(data_source, options = options)
    monthly_chart.html_id = 'monthlychart'
    subs = Submission.objects.filter(sub_made_by = request.user).order_by('-attempted')[:10]
    context = {
        'topic_chart':topic_chart,
        'monthly_chart':monthly_chart,
        'chart':chart,
        'submissions':subs,
        'active_tab':'profile',
    }
    return render(request, 'www/profile.html',context)
@login_required
def leaderboard(request):
    users = User.objects.all().order_by('-profile__experience_points')
    context = {
        'active_tab':'leaderboard',
        'users':users,
    }
    return render(request, 'www/leaderboard.html',context)
@login_required
def dashboard(request):
    query_set = Submission.objects.all().values('lang').annotate(langcount = Count('lang'))
    print query_set
    #data_source = ModelDataSource(query_set, fields=['user', 'experience_points', 'experience_points'],)
    row = list()
    data = list()
    data.append(['Langages', 'Submisions'])
    for query in query_set:
        languages = ConsoleLanguage.objects.filter(id = query.values()[0])
        for language in languages:
            row.append(language.lang)
        numbers = query.values()[1]
        row.append(numbers)
        data.append(row)
        row = list()
    print data
    #data.append(['c', '5']) not needed for production

    data_matrix =  [
            data
        ]
    data_source = SimpleDataSource(data=data)
    # chart = morris.DonutChart(data_source)
    options = {
        'title':'Language wise submissions',
        'subtitle': "Total submissions: " + str(Submission.objects.count()),

    }
    chart_language = highcharts.PieChart(data_source, options=options)
    chart_language.html_id = "languagesubmissions"
    # Preparing chart for problem difficulty levels
    query_set = Problem.objects.all().values('difficulty').annotate(difficulty_count = Count('difficulty'))
    print query_set
    data = list()
    row = list()
    data.append(['Difficulty', 'Problem Count'])
    for query in query_set:
        row.append(get_difficulty_verbose(query['difficulty']))
        row.append(query['difficulty_count'])
        data.append(row)
        row = list()
    print data
    data_source = SimpleDataSource(data)
    options = {
        'title':'Problem distribution : Difficulty wise',
        'subtitle': "Total Problems: " + str(Problem.objects.count()),

    }
    chart_difficulty = highcharts.ColumnLineChart(data_source, options=options)
    context = {
        'chart_language':chart_language,
        'chart_difficulty':chart_difficulty,
        'active_tab':'dashboard',
    }
    chart_difficulty.html_id = "difficultychart"
    return render(request, 'www/dashboard.html', context)

def get_difficulty_verbose(c):
    if c == 'E':
        return "Easy"
    elif c == "M":
        return "Medium"
    elif c == "H":
        return "Hard"
    else:
        return "Expert"

@login_required
def create_profile(request):
    if request.method == 'POST':
        form = ProfileForm(request.POST, request.FILES)
        user_profile, created = Profile.objects.get_or_create(user = request.user)
        if form.is_valid():
            user_type = form.cleaned_data['user_type']
            user_profile.user_avatar = request.FILES.get('user_avatar')
            user_profile.user_type = user_type
            user_profile.user = request.user
            user_profile.save()
            print user_profile
            # user_profile.save()
            return HttpResponseRedirect(reverse('ev:evhome'))
    else:
        form = ProfileForm()
        form.user = request.user
    
    context = {
        'form':form,
    }
    return render(request,'www/create_profile.html',context)

codecrunchers/www/templates/www/accounts_base.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load staticfiles %}
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0"/>
    <title>Code crunchers</title>
    {#Bootstrap4 css#}
    {#    <link rel="stylesheet" type="text/css" href="{% static 'bootstrap/css/bootstrap.min.css' %}"/>#}

    <link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous"/>

    {# Font-awesome   #}
    <link rel="stylesheet" type="text/css"
          href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
    {#JQuery#}
    <script src="https://code.jquery.com/jquery-3.1.1.min.js"></script>
    {#IntercoolerJS - AJAX on Steroids #}
    <script src="http://cdn.intercoolerjs.org/intercooler-1.1.0.min.js"></script>
    <link rel="stylesheet" type="text/css" href="{% static 'base/UserProfile.css' %}"/>
    </head>
<body>
    {% block content %}
    {% endblock %}
</body>
</html>

codecrunchers/www/templates/www/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load staticfiles %}
    {% load humanize %}
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0"/>

    <meta property="og:url"           content="http://codecrunchers.herokuapp.com" />
    <meta property="og:type"          content="website" />
    <meta property="og:title"         content="Where Code is Religion" />
    <meta property="og:description"   content="An online code programming website built totally in Python using Django" />
    <meta property="og:image"         content="https://d31v04zdn5vmni.cloudfront.net/blog/wp-content/uploads/2012/02/featured-image-snippets-1-690x362.png" />

    <title>Code crunchers</title>
    {#Bootstrap4 css#}
    {#    <link rel="stylesheet" type="text/css" href="{% static 'bootstrap/css/bootstrap.min.css' %}"/>#}

    <link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous"/>

    {# Font-awesome   #}
    <link rel="stylesheet" type="text/css"
          href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
    {#JQuery#}
    <script src="https://code.jquery.com/jquery-3.1.1.min.js"></script>
    <link rel="stylesheet" type="text/css" href="{% static 'base/UserProfile.css' %}"/>
    <link href="https://fonts.googleapis.com/css?family=Pacifico" rel="stylesheet"/>
    <style type="text/css">
        body {
            #background-color: #8BCBDE;
            #background-color: #87E8C6;
            #background-color: #158B93;
        }

        #prof-pic {
            border-radius: 50%;
            border: 3px solid white;
        }

        .profile-sidebar center {
        {#            background-color: #E3ECF2;#} #background-color: #64DDBB;
            background-color: #66CC99;
        }

        {#Copied code from somewhere and edited  for profile image hover animation#}
        * {
            -moz-box-sizing: border-box;
            -webkit-box-sizing: border-box;
            box-sizing: border-box;
            margin: 0;
            padding: 0;
        }

        .profile-sidebar center {
            position: relative;
            margin: 2%;
            overflow: hidden;
        }

        .profile-sidebar center {
            max-width: 100%;

            -moz-transition: all 0.3s;
            -webkit-transition: all 0.3s;
            transition: all 2s;

        }

        .profile-sidebar center img {
            transition-duration: 2s;
        }

        .profile-sidebar center img:hover {
            -moz-transform: scale(1.1);
            -webkit-transform: scale(1.1);
            transform: scale(2);
            transition-duration: 2s;
        }

        {#End of copied code from somewhere for profile image hover animation#}
        {#  Copied code for arrow scroll to top      #}
        {#     Scroll to top taken from here   https://codepen.io/rdallaire/pen/apoyx#}
        #return-to-top {
            position: fixed;
            bottom: 20px;
            right: 20px;
            background: rgb(0, 0, 0);
            background: rgba(0, 0, 0, 0.7);
            width: 50px;
            height: 50px;
            display: block;
            text-decoration: none;
            -webkit-border-radius: 35px;
            -moz-border-radius: 35px;
            border-radius: 35px;
            display: none;
            -webkit-transition: all 0.3s linear;
            -moz-transition: all 0.3s ease;
            -ms-transition: all 0.3s ease;
            -o-transition: all 0.3s ease;
            transition: all 0.3s ease;
        }

        #return-to-top i {
            color: #fff;
            margin: 0;
            position: relative;
            left: 16px;
            top: 13px;
            font-size: 19px;
            -webkit-transition: all 0.3s ease;
            -moz-transition: all 0.3s ease;
            -ms-transition: all 0.3s ease;
            -o-transition: all 0.3s ease;
            transition: all 0.3s ease;
        }

        #return-to-top:hover {
            background: rgba(0, 0, 0, 0.9);
        }

        #return-to-top:hover i {
            color: #fff;
            top: 5px;
        }

        {#        End of copied code for scroll to top#}

        {#        Logo header#}

        #logo-main {
            display: block;
            margin: 20px auto;
            position: static;
            font-family: 'Pacifico', cursive;
        }

        a:hover {
            text-decoration: none;
        }

        a {
            text-decoration: none;
        }

        {#     End of logo header   #}
        .container-fluid .container {
            padding-left: 0;
            padding-right: 0;
        }
        hr{
            #background-color: #66cc99;
            background-color: #4B77BE;
            height: 2px;
        }
        .singlehr{
            background-color: #66cc99;
            height: 3px;
        }
    </style>

</head>
<body>
<header role="banner">
    <h1 id="logo-main" class="text-center"><a href="{% url 'sitehome' %}">Code <i class="fa fa-code"></i>
        Crunchers</a><span class="h3"><small>Beta</small></span></h1>

</header>
<div class="container">
    <hr class="singlehr">
    <div class="row profile">
        <div class="col-md-3 col-lg-3 col-sm-4 col-xs-12">
            <div class="profile-sidebar">
                <center>

{#                    {% ifequal "profileimages/anonymous.jpg" user.profile.user_avatar %}#}
{#                        <img src="https://home.questionbig.com/images/avatar_blank.png" height="100" width="100"#}
{#                             id="prof-pic"/>#}
{#                    {% else %}#}
{#                        <img src="{{ MEDIA_URL }}{{ user.profile.user_avatar }}" height="100" width="100"#}
{#                             id="prof-pic"/>#}
{##}
{#                    {% endifequal %}#}
                    {% ifnotequal "profileimages/anonymous.jpg" user.profile.user_avatar %}
                        {% if user.profile %}
                        <img src="{{ MEDIA_URL }}{{ user.profile.user_avatar }}" height="100" width="100"#}
                             id="prof-pic"/>
                            {% else %}
                            <img src="https://home.questionbig.com/images/avatar_blank.png" height="100" width="100"#}
                             id="prof-pic"/>
                        {% endif %}
                    {% else %}
                        <img src="https://home.questionbig.com/images/avatar_blank.png" height="100" width="100"#}
                             id="prof-pic"/>
                    {% endifnotequal %}
                </center>
                <!-- END SIDEBAR USERPIC -->
                <!-- SIDEBAR USER TITLE -->
                <div class="profile-usertitle">
                    <div class="profile-usertitle-name">
                        {% if user.is_authenticated %}
                            <span id="repName">{{ user.first_name }} {{ user.last_name }}</span>
                            <br>
                            <small><span id="repName">@{{ user }}</span></small>
                        {% endif %}
                    </div>
                    <div class="profile-usertitle-job">
                        <span id="compName">{{ user.profile.get_usertype_verbose }}</span>
                    </div>
                    <div>
                        <i class="fa fa-trophy fa-2x"></i>
                        Experience Points {{ user.profile.experience_points }}
                    </div>
                </div>
                <!-- END SIDEBAR USER TITLE -->

                <!-- SIDEBAR MENU -->
                <div class="profile-usermenu">
                    <ul class="nav">
                        {% if user.is_authenticated %}
                            <li class="{% if active_tab == 'profile' %}active{% endif %}">
                                <a href="{% url 'profile' %}">
                                    <i class="glyphicon glyphicon-user"></i>
                                    Profile </a>
                            </li>
                        {% endif %}
                        <li class="{% if active_tab == 'leaderboard' %}active{% endif %}">
                            <a href="{% url 'leaderboard' %}">
                                <i class="glyphicon glyphicon-stats"></i>
                                Leaderboard</a>
                        </li>
                        {% if user.is_staff %}
                            <li class="{% if active_tab == 'dashboard' %}active{% endif %}">
                                <a href="{% url 'dashboard' %}">
                                    <i class="fa fa-pie-chart"></i>
                                    Dashboard</a>
                            </li>
                        {% endif %}

                        <li class="{% if active_tab == 'problems' %}active{% endif %}">
                            <a href="{% url 'ev:evhome' %}">
                                <i class="fa fa-code"></i>
                                Problems</a>
                        </li>

                        <li class="{% if active_tab == 'prac_home' %}active{% endif %}">
                            <a href="{% url 'ev:contest_home' %}">
                                <i class="fa fa-folder"></i>
                                Contests</a>
                        </li>

                        <li class="{% if active_tab == 'console' %}active{% endif %}">
                            <a href="{% url 'cc:console' %}" target="_blank">
                                <i class="fa fa-terminal" aria-hidden="true"></i>
                                Console</a>
                        </li>
                        {% if user.is_staff %}
                            <li>
                                <a href="/admin" target="_blank">
                                    <i class="fa fa-users" aria-hidden="true"></i>
                                    Admin</a>
                            </li>
                        {% endif %}
                        <li>
                            {% if user.is_authenticated %}
                                <a href="{% url 'auth_logout' %}">
                                    <i class="glyphicon glyphicon-log-out"></i>
                                    Sign Out</a>
                            {% else %}
                                <a href="{% url 'auth_login' %}">
                                    <i class="glyphicon glyphicon-log-in"></i>
                                    Sign In</a>
                            {% endif %}
                        </li>
                    </ul>
                </div>
                <!-- END MENU -->


            </div>

        </div>

        {% block content %}
        {% endblock %}

    </div>

    <a href="javascript:" id="return-to-top"><i class="fa fa-arrow-up"></i></a>
    <hr class="singlehr">
    <footer class="text-center">
        <h4 id="logo-main">&copy; 2017 Code <i class="fa fa-code"></i> crunchers</h4>
    </footer>
</div>

<script>
    {#    $(document).ready(function () {#}
    {#        $("li").hover(function () {#}
    {#            $(this).addClass("active");#}
    {#        }, function () {#}
    {#            $(this).removeClass("active");#}
    {#        })#}
    {#    });#}
    {#    $("li").click(function () {#}
    {#        $(this).addClass("active");#}
    {#    });#}
    {#     ===== Scroll to Top ====#}
    $(window).scroll(function () {
        if ($(this).scrollTop() >= 50) {        // If page is scrolled more than 50px
            $('#return-to-top').fadeIn(200);    // Fade in the arrow
        } else {
            $('#return-to-top').fadeOut(200);   // Else fade out the arrow
        }
    });
    $('#return-to-top').click(function () {      // When arrow is clicked
        $('body,html').animate({
            scrollTop: 0                       // Scroll to top of body
        }, 500);
    });
    {#     ===== Scroll to Top Ends====#}
</script>
</body>
</html>

codecrunchers/www/templates/www/create_profile.html
{% extends 'www/base.html' %}
{% block content %}
<style>
    .error{
        color: red;
        text-justify: auto;
    }
    </style>
<div class="col col-lg-9 col-md-9 col-sm-8 col-xs-12">
    <div class="container-fluid">
    <h2>Manage Your Profile</h2>
    <hr>
    <div class="col-lg-5">
    <form id="user_profile" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <button class="btn btn-primary" value="submit" name="Submit">Submit</button>
    </form>
    </div>
    </div>
</div>
<script>
    $("#id_user_type").addClass("form-control");
    $("#id_user_type").addClass("btn-file");
    $("li").addClass("error");
</script>
{% endblock %}

codecrunchers/www/templates/www/dashboard.html
{% extends 'www/base.html' %}
{% load staticfiles %}

{% block content %}
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/highcharts/5.0.10/css/highcharts.css"/>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/highcharts/5.0.10/highcharts.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/highcharts/5.0.10/js/modules/exporting.js"></script>
    <style>
        .graph_holder {
            width: 50%;
        }

        #languagesubmissions, #difficultychart {
            max-width: 285px;
            padding-top: 10px;
        }
    </style>
    <div class="col col-lg-9 col-md-9 col-sm-8 col-sm-12 col-xs-12">

        <div class="container-fluid">
            <h2>Dashboard</h2>
            <hr>
            <div class="row">

                <div class="col col-lg-4 col-md-4 col-sm-12">

                    {{ chart_language.as_html }}
                </div>
                <div class="col col-lg-4 col-lg-offset-2 col-md-4 col-md-offset-3 col-sm-12 col-xs-12">
                    {{ chart_difficulty.as_html }}
                </div>
            </div>
            <br>


        </div>
    </div>
{% endblock %}

codecrunchers/www/templates/www/leaderboard.html
{% extends 'www/base.html' %}
{% block content %}
    
    <!-- -->
    <script>
        (function(d, s, id) {
        var js, fjs = d.getElementsByTagName(s)[0];
        if (d.getElementById(id)) return;
        js = d.createElement(s); js.id = id;
        js.src = "//connect.facebook.net/en_US/sdk.js#xfbml=1&version=v2.8&appId=276041826164974";
        fjs.parentNode.insertBefore(js, fjs);
        }(document, 'script', 'facebook-jssdk'));
    </script>
    <!-- -->

    <div id="fb-root"></div>
    <div class="col col-lg-9 col-md-9 col-sm-8 col-xs-12">
    <h2>Leaderboard</h2>
    <div id="shareBtn" class="label btn label-primary">Share on facebook &nbsp;<span class="fa-2x fa fa-facebook-square" aria-hidden="true" style="cursor: pointer;"></span></div>
    <hr>
        <div class="table-responsive">
        <table class="table table-bordered panel text-center">
            <thead>
            <tr>
            <th class="panel-title text-center">Rank</th>
            <th class="panel-title text-center">User</th>
            <th class="panel-title text-center">Username</th>
            <th class="panel-title text-center">Points</th>
           </tr>
            </thead>
        {% for user in users %}
            {% if user == request.user %}
                <tr class="btn-success">
                <td>{{forloop.counter}}</td>
                <td><img src="{{ MEDIA_URL }}{{ user.profile.user_avatar }}" height="50" width="50" id="prof-pic"/></td>
                <td>{{ user.username }}</td>
                <td id="success-user">{{ user.profile.experience_points }}</td>
            {% else %}
                <tr>
                <td>{{forloop.counter}}</td>
                <td><img src="{{ MEDIA_URL }}{{ user.profile.user_avatar }}" height="50" width="50" id="prof-pic"/></td>
                <td>{{ user.username }}</td>
                <td>{{ user.profile.experience_points }}</td>
            {% endif %}

                
            </tr>
        {% endfor %}
        </table>
        </div>
    </div>
    <script>
        document.getElementById('shareBtn').onclick = function() {
        FB.ui({
            method: 'share',
            display: 'popup',
            href: 'http://codecrunchers.herokuapp.com/',
            app_id: '276041826164974',
            quote: 'Show your coding skills and beat my XP : ' + document.getElementById("success-user").innerHTML,
        }, function(response){});
        }
    </script>
{% endblock %}

codecrunchers/www/templates/www/password.html
{% extends 'base.html' %}

{% block content %}
  <h2>Change Password</h2>
  {% if not user.has_usable_password %}
    <p style="color: red">You have not defined a password yet.</p>
  {% endif %}
  <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Save changes</button>
  </form>
{% endblock %}